# https://raw.githubusercontent.com/DavidAnson/markdownlint/refs/heads/main/schema/.markdownlint.yaml
---
default: true

MD007:
  indent: 4

MD013:
  line_length: 120
  code_blocks: false
  tables: false

MD024:
  siblings_only: true
